spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///sun-seckill
    username: root
    password: 1111

#  redis:
#    host: cd-crs-equq6k9o.sql.tencentcdb.com
#    port: 23250
#    password: SUN123456


mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.sixsixsix516.seckill.model
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

